# docker_compose.raw

version: '3.8'

services:
  vpn_shell:
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    build: .
    volumes:
      - .:/base
      - ./configs/etc_windscribe:/etc/windscribe/
      - ./configs/root_azure:/root/.azure/
    command: bash -c /base/compose.rc

volumes:
  etc_windscribe:
  root_azure:

