#!/bin/bash
# upd_silent_ids

. $(dirname "$0")/farm.creds # ssh creds

HOSTS_FILE=/etc/hosts
DIRNAMES='terradocean terrazure'
LIB_FILENAME=upd_hosts_lib
HOSTS_EXCL_MASK='# farm'

SLASH_N_HOSTS=''    
TERRAFORM_ADDRS='' 
echo Updating hosts file with farm addresses
for DIRNAME in $DIRNAMES ; do
  if [ -f /base/$DIRNAME/$LIB_FILENAME ] ; then
    . /base/$DIRNAME/$LIB_FILENAME # import get_terraform_slash_n_hosts()
    # cd /base/$DIRNAME
    get_terraform_slash_n_hosts
  fi
done
#OLD_HOSTS=$(grep -v "$HOSTS_EXCL_MASK" $HOSTS_FILE | tr \\n \~)
#echo $OLD_HOSTS | tr \~ \\n | sed '/^$/d' > $HOSTS_FILE
#echo -e $SLASH_N_HOSTS >> $HOSTS_FILE
echo -e Processed farm hostnames are:\\n$TERRAFORM_ADDRS

# mk silent ssh to farm 
for SRV in $TERRAFORM_ADDRS ; do
  echo -e "\\nProcessing "$SRV":"
  # ssh keys actions
  sshpass -p $RMT_PW \
   ssh-copy-id \
     -o StrictHostKeyChecking=no \
     $RMT_USERNAME@$SRV
   # change rmt screen hotkey
   ssh $RMT_USERNAME'@'$SRV\
       ' echo '$RMT_PW' | sudo -S bash -c "if [ `grep escape /etc/screenrc &> /dev/null ; echo $?` = 1 ] ; then echo escape\ ^Bb >> /etc/screenrc ; echo screenrc-modified ; else echo screenrc-is-already-modified ; fi"'
done

