#!/bin/bash
# upd_hosts

HOSTS_FILE=/etc/hosts
DIRS=terrazure
for DIR in $DIRS ; do
  cd /base/$DIR
  for i in $(\
    terraform show \
    | grep -E \
    '?(computer_name)|(public_ip_address[^"]+"[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)' \
    | grep -oE '"[0-9\.a-z]+"' | tr -d \" | tr \\n \~ \
    | grep -oE '[a-z0-9]+~[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' \
  ) ; do 
    IP=$(echo $i | sed -r 's/^[^~]+~//') 
    ADDR=$(echo $i | sed -r 's/~[^~]+$//')
    OLD_HOSTS=$(grep -v $ADDR $HOSTS_FILE | tr \\n \~)
    echo $OLD_HOSTS | tr \~ \\n | sed '/^$/d' > $HOSTS_FILE
    echo $IP $ADDR >> $HOSTS_FILE
  done  
done

